title: Mi página
iconURL: assets/default-icon.png
theme: jekyll-theme-hacker
description: Bookmark this to keep an eye on my project updates!

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
